baseURL         = "/"
title           = "Glasswall CDR Platform"
theme           = "hugo-theme-learn"
themesdir       = "../"
metaDataFormat  = "yaml"
contentDir      = "../content"
dataDir         = "../data"
canonifyURLs    = true
ignorefiles     = [ "aws/.*", "servers/.*", "status/.*", "workflows/.*" ]


[params]
  themeVariant    = "blue"
  disableSearch   = true
  disableNextPrev = true
  titleSeparator  = "-"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/filetrust/cdr-plugin-folder-to-folder"
target = "_blank"
weight = 10