version:  '3'
services:
  datascience-notebook:
      image: cdr_plugin_folder_to_folder_notebooks
      volumes:
        - ${PWD}/jupyter/notebooks:/home/jovyan/work
        - ${PWD}/test_data:/home/jovyan/test_data
      ports:
        #- ${PORT}:8888
      - 8888:8888
      container_name:   jupyter_notebook
      command: "start-notebook.sh \
                 --NotebookApp.token=${ACCESS_TOKEN}"