version:  '3.9'
services:
  jupyter:
      image: cdr_plugin_folder_to_folder_notebooks
      build:
        dockerfile: ${PWD}/jupyter/Dockerfile
        context: ${PWD}/jupyter
      volumes:
        - ${PWD}/jupyter/notebooks:/home/jovyan/work
        - ${PWD}/test_data:/home/jovyan/test_data
#      build:
#        context: jupyter
#        dockerfile: Dockerfile
      ports:
        - 8888:8888
      container_name: jupyter_notebook
      command: "start-notebook.sh \
                 --NotebookApp.token=${ACCESS_TOKEN}"

# Fast API

  api:
      image: cdr_plugin_folder_to_folder
      build:
        dockerfile: ${PWD}/cdr_plugin_folder_to_folder/Dockerfile
        context: ${PWD}/cdr_plugin_folder_to_folder
      volumes:
        - ${PWD}/cdr_plugin_folder_to_folder:/app/cdr_plugin_folder_to_folder
        - ${PWD}/test_data:/app/test_data
      ports:
        - 8880:8880

  # Elastic and Kibana

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kib01:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      #- logger.level=WARN
      #- logging.verbose=false
      #- logging.level=WARN
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=["http://es01:9200"]

  # minio

  minio:
    image: minio/minio:latest
    volumes:
      - ${PWD}/test_data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${ACCESS_TOKEN}
    command: server /data


  # docker logs (using file beat)

#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.12.0
#    user: root
#    volumes:
#      - ${PWD}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#      - /var/lib/docker:/var/lib/docker:ro
#      - /var/run/docker.sock:/var/run/docker.sock
