services: 
  minio:
    image: minio/minio:latest
    volumes:
      - ${HOST_MINIO_LOCATION}:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${ACCESS_TOKEN}
    command: server /data
    restart: always

version: "3.3"
