services: 
  website: 
    build: 
      context: "${PWD}/website"
      dockerfile: "${PWD}/website/Dockerfile"
    image: cdr_plugin_folder_to_folder_website
    ports: 
      - "1313:1313"
    restart: always
    volumes: 
      - "${PWD}/website/site:/src/site"
      - "${PWD}/website/content:/src/site/content"
      - "${PWD}/website/data:/src/site/data"
version: "3.3"

