apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/cdr-plugin: "runtime/default"
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "appname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.cdrplugin.repository }}:{{ .Values.image.cdrplugin.tag }}"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
        imagePullPolicy: {{ .Values.image.cdrplugin.pullPolicy }}
        {{- if .Values.application.cdrplugin.secrets }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.cdrplugin.secretName }}
        {{- end }}
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        {{- with .Values.application.cdrplugin.env }}
        {{- range $key, $val := . }}
        {{- if $val }}
          - name: "{{ tpl $key $  }}"
            value: "{{ tpl $val $  }}"
        {{- end }}
        {{- end }}
        {{- end }}

        volumeMounts:
        - name: hd1-vol
          mountPath: {{ .Values.application.cdrplugin.env.HD1_LOCATION }}
          readOnly: true
        - name: hd2-vol
          mountPath: {{ .Values.application.cdrplugin.env.HD2_LOCATION }}
        - name: hd3-vol
          mountPath: {{ .Values.application.cdrplugin.env.HD3_LOCATION }}
        ports:
        - name: "{{ .Values.service.cdrplugin.name }}"
          containerPort: {{ .Values.service.cdrplugin.internalPort }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.service.cdrplugin.internalPort }}
            scheme: {{ .Values.livenessProbe.scheme }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.service.cdrplugin.internalPort }}  
            scheme: {{ .Values.readinessProbe.scheme }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        {{- end }}
        resources:
{{ toYaml .Values.resources.cdrplugin | indent 12 }}
      {{- if .Values.hostAliases }}
      {{- with .Values.hostAliases }}
      hostAliases:
      {{- range $key, $val :=  . }}
      - ip: {{ $key }}
        hostnames:
        {{- range $hostname := $val }}
        - {{ $hostname }}
        {{- end -}}
      {{- end}}
      {{- end}}
      {{- end}}
      volumes:
      - name: hd1-vol
        persistentVolumeClaim:
          claimName: hd1-pvc
      - name: hd2-vol
        persistentVolumeClaim:
          claimName: hd2-pvc
      - name: hd3-vol
        persistentVolumeClaim:
          claimName: hd3-pvc
      
