# This is a workflow to update the CI server with latest code from main branch

name: cdr-plugin-ci
env:
  AWS_DEFAULT_REGION: eu-west-1
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
     - main

jobs:
  deploy-cdr-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Update CDR pluging folder to folder
        uses: appleboy/ssh-action@master
        with:
          host: "34.253.17.169"
          username: ubuntu
          key: '${{ secrets.SSH_KEY }}'
          script: |
            set -e
            cd ~/cdr-plugin-folder-to-folder/
            chmod +x bin/ci-update-server.sh
            ./bin/ci-update-server.sh
            