name: Run BDD Smoke Tests
on:
  push:
    branches:
      - main
      - develop
      - bdd_test_integration
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: install docker and docker-compose
        run: |
          sudo apt-get install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install docker-ce docker-ce-cli containerd.io -y
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: remove previous state from f2f
        run: |
          rm -rf test_data/scenario-1/hd2 test_data/scenario-1/hd3 test_data/scenario-2/hd2 test_data/scenario-2/hd3
      - name: Start Folder to Folder Containers
        run: |
          cp .env.sample .env
          source .env.sample
          docker-compose build
          docker-compose up -d --force
          sleep 120s
      - name: Install dependencies for Behave test
        run: |
          python -m pip install --upgrade pip
          pip install -r cdr-plugin-f2f-automation-tests/tests/requirements.txt
      - name: Run tests with Behave
        run: |
          cd cdr-plugin-f2f-automation-tests/tests/
          behave
